name: CI

on:
  push:
    branches:
      - main
      - staging
      - release/*
  pull_request:
    branches:
      - main
      - staging
      - release/*
  workflow_dispatch:
    inputs:
      nussknacker_version:
        description: "Nussknacker version"
        required: false
        type: string

env:
  NUSSKNACKER_VERSION: ${{ inputs.nussknacker_version }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update root CA
        run: sudo update-ca-certificates -f
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: "openjdk@1.11"
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew build